FROM --platform=linux/amd64 tensorflow/tensorflow:2.14.0-gpu
RUN pip install wandb==0.16.6 && \
    pip install pandas==2.2.2 && \
    pip install nltk==3.9.1

ENTRYPOINT [ "/bin/bash" ]
VOLUME [ "/storage" ]
