kind: Job
apiVersion: batch/v1
metadata:
  name: gene-embedding
spec:
  template:
    spec:
      hostIPC: true
      containers:
      - name: gene-embedding
        image: "theodorross/tensorflow-experiments:cuda-v0.3"
        command: ["python"]
        args:
        - "train_gene_autoencoder.py"
        - "--platform=springfield"
        - "--dataset=dev"
        - "--learning-rate=5e-4"
        - "--batch-size=8"
        - "--epochs=50"
        - "--patience=5"
        - "--embedding-dim=2"
        - "--encoder-layers=1"
        - "--decoder-layers=1"
        - "--key-dim=16"
        - "--num-heads=4"
        - "--ff-dim=32"
        workingDir: /storage/genome_transformer_dev/gene_embedding
        volumeMounts:
        - name: storage
          mountPath: /storage
        resources:
          limits:
            memory: "16Gi"
        env: 
        - name: WANDB_API_KEY
          valueFrom: 
            secretKeyRef: 
              name: wandb
              key: apikey
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0