kind: Job
apiVersion: batch/v1
metadata:
  name: gene-embedding
spec:
  template:
    spec:
      hostIPC: true
      containers:
      - name: gene-embedding
        image: "theodorross/tensorflow-experiments:cuda-v0.3"
        command: ["python"]
        args:
        - "train_gene_autoencoder.py"
        - "--platform=springfield"
        - "--dataset=dev"
        - "--learning-rate=1e-4"
        - "--learning-rate-decay=0.01"
        - "--learning-rate-decay-start=75"
        - "--masking-rate=0.25"
        - "--batch-size=8"
        - "--epochs=400"
        - "--patience=50"
        - "--embedding-dim=64"
        - "--encoder-layers=3"
        - "--decoder-layers=3"
        - "--key-dim=64"
        - "--num-heads=8"
        - "--ff-dim=2048"
        - "--n-sequence-tokens=1"
        - "--max-seq-length=100"
        workingDir: /storage/genome_transformer_dev/gene_embedding
        volumeMounts:
        - name: storage
          mountPath: /storage
        resources:
          limits:
            memory: "32Gi"
        env: 
        - name: WANDB_API_KEY
          valueFrom: 
            secretKeyRef: 
              name: wandb
              key: apikey
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0