kind: Job
apiVersion: batch/v1
metadata:
  name: gene-embedding-full
spec:
  template:
    spec:
      hostIPC: true
      containers:
      - name: gene-embedding-full
        image: "theodorross/tensorflow-experiments:cuda-v0.3"
        command: ["python"]
        args:
        - "train_gene_autoencoder.py"
        - "--platform=springfield"
        - "--dataset=full"
        - "--n-sequence-tokens=8"
        - "--latent-dim=32"
        - "--embedding-dim=6"
        - "--learning-rate=5e-3"
        - "--learning-rate-decay=1e-3"
        - "--learning-rate-decay-start=1000"
        - "--masking-rate=0.0"
        - "--dropout-rate=0.0"
        - "--batch-size=30"
        - "--epochs=1000"
        - "--patience=150"
        - "--encoder-layers=1"
        - "--decoder-layers=1"
        - "--key-dim=8"
        - "--num-heads=12"
        - "--ff-dim=32"
        - "--max-seq-length=100"
        - "--decode-length=100"
        workingDir: /storage/genome_transformer_dev/gene_embedding
        volumeMounts:
        - name: storage
          mountPath: /storage
        resources:
          limits:
            memory: "32Gi"
        env: 
        - name: WANDB_API_KEY
          valueFrom: 
            secretKeyRef: 
              name: wandb
              key: apikey
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0